# Live model
model: fofr/any-comfyui-workflow

# A private model to run the test against before pushing
test_model: fofr/any-comfyui-workflow-staging
test_hardware: gpu-l40s

# Tests
predict:
  compare_outputs: false
  predict_timeout: 600
  test_cases:
    # - inputs:
    #     workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/hunyuan_video_image_to_video_api.json
    #     return_temp_files: true
    # - inputs:
    #     workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/sd15_txt2img.json
    #     return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/wan_21_13b_t2v_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/flux_pulid_with_attn_mask_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/advanced_live_portrait_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/brushnet_powerpaint_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/comfyui_essentials_all_workflows.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/glif_custom_lora_flux_hf.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/instantid_default_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/ipadapter_faceid.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/kolors_and_ipadapter_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/reactor_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/reactor_with_face_swap_opt_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/birefnet_ii_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/birefnet_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/depth_anything_v2_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/fbcnn_api.json
    - error_contains: "ComfyUI API nodes are not currently supported"
      inputs:
        workflow_json: https://raw.githubusercontent.com/replicate/cog-comfyui/refs/heads/main/examples/api_workflows/comfyui_api_node_api.json
